USE PrestigeCars

GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
-- Color Table
DROP TABLE IF EXISTS Data.Color
CREATE TABLE [Data].[Color](
	[ColorID] [Udt].[SurrogateKeyInt] IDENTITY(1,1) NOT NULL,
	[Color] [Udt].[Color] NOT NULL,
 CONSTRAINT [PK_Color] PRIMARY KEY CLUSTERED 
(
	[ColorID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]


-- PivotTable Table
DROP TABLE IF EXISTS Data.PivotTable
GO
CREATE TABLE [Data].[PivotTable](
	[ColorID] [Udt].[SurrogateKeyInt] NOT NULL,
	[2015] [Udt].[Year2015] NULL,
	[2016] [Udt].[Year2015] NULL,
	[2017] [Udt].[Year2015] NULL,
	[2018] [Udt].[Year2015] NULL,
 CONSTRAINT [PK_PivotTable] PRIMARY KEY CLUSTERED 
(
	[ColorID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]

--Alter FK and additional contstraints 
ALTER TABLE [Data].[PivotTable]  WITH CHECK ADD  CONSTRAINT [FK_PivotTable_Color] FOREIGN KEY([ColorID])
REFERENCES [Data].[Color] ([ColorID])
GO
ALTER TABLE [Data].[PivotTable] CHECK CONSTRAINT [FK_PivotTable_Color]
GO